name: Wakatime

on:
  # workflow_dispatch:
  schedule:
    - cron: '0 15 * * *' # 12:00 am (JST)
    - cron: '11 14 * * *' # 11:11 pm (JST)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@0.1.3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
